## Indexación (indexing) y segmentación (slicing) de arrays 

In [1]:
import numpy as np

In [2]:
array = np.array([2,4,6,8,10])

# Acceder al elemento en la posición del array 
print('Accedemos al elemento del array: ')
print(f'El array de [0]: {array[0]}')
print(f'El array de [1]: {array[1]}')
print(f'El array de [2]: {array[2]}')
print(f'El array de [3]: {array[3]}')
print('\nLa dimensión del array es: ', {array.ndim})
print('\nEl shape del array es: ', {array.shape})

Accedemos al elemento del array: 
El array de [0]: 2
El array de [1]: 4
El array de [2]: 6
El array de [3]: 8

La dimensión del array es:  {1}

El shape del array es:  {(5,)}


In [3]:
sudoku_array = np.array([[1, 2, 3, 4, 5, 6],
                         [7, 8, 9, 10, 11, 12],
                         [13, 14, 15, 16, 17, 18],
                         [19, 20, 21, 22, 23, 24],
                         [25, 26, 27, 28, 29, 30],
                         [31, 32, 33, 34, 35, 36]])

print(f'La dimension del sudoku es: ', {sudoku_array.ndim})
print(sudoku_array)

La dimension del sudoku es:  {2}
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


La dimensión 2 se debe a que el array tiene una estructura de matriz, con 6 filas (PRIMERA DIMENSION) y 6 columnas (SEGUNDA DIMENSIÓN).

In [4]:
# Accedo a la primera fila
print(sudoku_array[0])  # Selecciona la primera fila

print('\nSelecciona todas las filas con (:), y la coma (,) indica que queremos mantener todas las columnas,')
print('y 3 especifica el índice de la columna: ')
print(sudoku_array[:,2]) #[:,]selecciona todas las filas 


[1 2 3 4 5 6]

Selecciona todas las filas con (:), y la coma (,) indica que queremos mantener todas las columnas,
y 3 especifica el índice de la columna: 
[ 3  9 15 21 27 33]


In [5]:
#Selecciono el 16
print(sudoku_array[2,3])

16


In [6]:
#Selecciono el 35
print(sudoku_array[5,4])

35


In [7]:
print(sudoku_array[2,:])

[13 14 15 16 17 18]


### Slicing arrays 1D

In [8]:
array = np.array([2,4,6,8,10])
array[2:4]

array([6, 8])

### Slicing arrays 2D

In [9]:
sudoku_array1 = np.array([[10, 2, 3, 4, 5, 6],
                         [70, 800, 9, 100, 11, 120],
                         [13, 14, 15, 16, 17, 18],
                         [19, 200, 21, 220, 23, 240],
                         [25, 26, 27, 28, 29, 30],
                         [30, 302, 33, 340, 35, 360]])

print(f'La dimension del sudoku es: ', {sudoku_array1.ndim})
print(sudoku_array1)

La dimension del sudoku es:  {2}
[[ 10   2   3   4   5   6]
 [ 70 800   9 100  11 120]
 [ 13  14  15  16  17  18]
 [ 19 200  21 220  23 240]
 [ 25  26  27  28  29  30]
 [ 30 302  33 340  35 360]]


In [10]:
sudoku_array1[1:6:2, 1:6:2]
             #Filas  #Columnas

array([[800, 100, 120],
       [200, 220, 240],
       [302, 340, 360]])

## Ordenando arrays:

In [11]:
np.sort(sudoku_array1)

array([[  2,   3,   4,   5,   6,  10],
       [  9,  11,  70, 100, 120, 800],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  21,  23, 200, 220, 240],
       [ 25,  26,  27,  28,  29,  30],
       [ 30,  33,  35, 302, 340, 360]])

## Filtrado de arrays

Hay 2 formas de filtrar en Numpy: 

* Idexado usando `mask` y `fancy`

* Usando `np.where()`

### Indexando con Boolean mask: 

In [12]:
one_to_five = np.arange(1,6)
one_to_five

array([1, 2, 3, 4, 5])

In [13]:
mask = one_to_five % 2 == 0
mask

array([False,  True, False,  True, False])

### Filtrado usando 'fancy indexing' 

In [14]:
one_to_five = np.arange(1, 6) 
mask = one_to_five % 2 == 0
one_to_five[mask]

array([2, 4])

### 2D facing indexing 

In [15]:
clases_id_edad = np.array([[1,22], [2, 21], [3,27], [4,26]])
print(clases_id_edad.ndim)
clases_id_edad


2


array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [16]:
clases_id_edad[:,1] % 2 ==  0

array([ True, False, False,  True])

### Fancy indexing vs np.where()

* Fancy indexing, retorna un array de elementos 
* np.where(), retorna un array de índices. 

### Filttado con np.where()


In [17]:
np.where(clases_id_edad[:,1] % 2 == 0)

(array([0, 3], dtype=int64),)

### Obtención de elementos con np.where()

In [18]:
#array 2D 
array = np.array([
    [1, 2, 3, 0, 5],
    [6, 0, 8, 9, 10],
    [11, 12, 13, 14, 0],
    [15, 16, 17, 18, 19]
])

print("Consume",array.nbytes,"bytes") 

Consume 80 bytes


Queremos encontrar los índices de las filas y columnas donde se encuentran los ceros en el array. Para hacer esto, podemos utilizar np.where() de la siguiente manera:

In [19]:
row_ind, col_ind = np.where(array == 0)

print(f'Los ceros se encuentran en las filas: {row_ind}')
print(f'Los ceros se encuentran en las columnas: {col_ind}')

Los ceros se encuentran en las filas: [0 1 2]
Los ceros se encuentran en las columnas: [3 1 4]


## Encontrar y reemplazar 

In [20]:
np.where(array == 0, " ", array)

array([['1', '2', '3', ' ', '5'],
       ['6', ' ', '8', '9', '10'],
       ['11', '12', '13', '14', ' '],
       ['15', '16', '17', '18', '19']], dtype='<U11')

## Concatenación

### Concatenación de filas 

La función np.concatenate concatenará los arrays en la dirección de las filas (axis=0 por defecto), por lo que el shape final será (n1 + n2, 2), donde n1 y n2 son el número de filas de cada array.

In [21]:
classroom_ids_and_sizes = np.array([[1,22], [2,21],[3,27],[4,26]])
new_classrooms = np.array([[5,30], [5,17]])

print(classroom_ids_and_sizes.ndim)
#el atributo shape de un array devuelve una tupla, (n_filas, n_columnas).
print(classroom_ids_and_sizes.shape)
print(classroom_ids_and_sizes)

print('--------------')
print(new_classrooms.ndim)
print(new_classrooms.shape)
print(new_classrooms)

print('\n==============')
concatenado_filas = np.concatenate((classroom_ids_and_sizes, new_classrooms))
print(concatenado_filas.shape)
concatenado_filas

2
(4, 2)
[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]
--------------
2
(2, 2)
[[ 5 30]
 [ 5 17]]

(6, 2)


array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26],
       [ 5, 30],
       [ 5, 17]])

### Concatenación de columnas 

In [22]:
classroom_ids_and_sizes = np.array([[1,22],[2,21],[3,27],[4,26]])
grade_levels_and_teachers = np.array([[1,'Jordi'], [1,'Mario'], [3,'Quintin'], [3,'Sofi']])
print("Consume",classroom_ids_and_sizes.nbytes,"bytes") 

print('El array --> classroom_ids_and_size')
print(classroom_ids_and_sizes)
print(f' Tiene shape de: ', classroom_ids_and_sizes.shape)
print(f' Tiene dimensión de: ', classroom_ids_and_sizes.ndim)
print('-----------------------------------------')
print('El array --> grade_levels_and_teachers')

print(grade_levels_and_teachers)
print(f' Tiene shape de: ', grade_levels_and_teachers.shape)
print(f' Tiene dimensión de: ', grade_levels_and_teachers.ndim)

print('\n==========================================')
print('\nEl array --> concatenado_columnas')
concatenado_columnas = np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)

print(f' Tiene shape de: ', concatenado_columnas.shape)
print(f' Tiene dimensión de: ', concatenado_columnas.ndim)
concatenado_columnas

Consume 32 bytes
El array --> classroom_ids_and_size
[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]
 Tiene shape de:  (4, 2)
 Tiene dimensión de:  2
-----------------------------------------
El array --> grade_levels_and_teachers
[['1' 'Jordi']
 ['1' 'Mario']
 ['3' 'Quintin']
 ['3' 'Sofi']]
 Tiene shape de:  (4, 2)
 Tiene dimensión de:  2


El array --> concatenado_columnas
 Tiene shape de:  (4, 4)
 Tiene dimensión de:  2


array([['1', '22', '1', 'Jordi'],
       ['2', '21', '1', 'Mario'],
       ['3', '27', '3', 'Quintin'],
       ['4', '26', '3', 'Sofi']], dtype='<U11')

## Borrar con np.delete()

In [23]:
data_clases = np.array([['1', '22', '1', 'James'],
                        ['2', '21', '1', 'George'],
                        ['3', '27', '2', 'Peter'],
                        ['4', '26', '2', 'Anna']])

In [24]:
#Borrando filas 
np.delete(data_clases, 1, axis=0)

array([['1', '22', '1', 'James'],
       ['3', '27', '2', 'Peter'],
       ['4', '26', '2', 'Anna']], dtype='<U6')

In [25]:
#Borrando columnas: 
np.delete(data_clases, 1, axis=1)

array([['1', '1', 'James'],
       ['2', '1', 'George'],
       ['3', '2', 'Peter'],
       ['4', '2', 'Anna']], dtype='<U6')

In [26]:
np.delete(data_clases, 0, axis=1)

array([['22', '1', 'James'],
       ['21', '1', 'George'],
       ['27', '2', 'Peter'],
       ['26', '2', 'Anna']], dtype='<U6')

In [27]:
#Borrar sin especificar 
np.delete(data_clases, 1)

array(['1', '1', 'James', '2', '21', '1', 'George', '3', '27', '2',
       'Peter', '4', '26', '2', 'Anna'], dtype='<U6')

## Métodos de Agregación

* .sum()
* .min()
* .max()
* .mean()
* .cumsum()

In [28]:
security_breaches = np.array([[0,5,1],[0,2,0],[1,1,2],[2,2,1],[0,0,0]])
security_breaches

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

año 1  = cliente1(0) ---> cliente2(5)  ---> cliente3(1)

año 2  = cliente1(0) ---> cliente2(2)  ---> cliente3(0)
.
.
.

año 5  = cliente1(0) ---> cliente2(0)  ---> cliente3(0)

## Sumando datos

In [29]:
print(security_breaches.sum())

17


In [30]:
print(security_breaches.sum(axis = 1)) # suma filas 

[6 2 4 5 0]


In [31]:
print(security_breaches.sum(axis = 0)) #suma columnas 

[ 3 10  4]


## Valores mínimo y valores máximo 

In [32]:
security_breaches.min()

0

In [33]:
security_breaches.max()

5

In [34]:
security_breaches.min(axis=1) # Pr fila selecciona el mínimo 

array([0, 0, 1, 1, 0])

In [35]:
security_breaches.min(axis=0)

array([0, 0, 0])

## Media: mean()

In [36]:

security_breaches.mean()

1.1333333333333333

In [37]:
security_breaches

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

In [38]:
# media de las filas 
security_breaches.mean(axis=1) #Por filas 

array([2.        , 0.66666667, 1.33333333, 1.66666667, 0.        ])

In [39]:
security_breaches.mean(axis=1, keepdims=True)

array([[2.        ],
       [0.66666667],
       [1.33333333],
       [1.66666667],
       [0.        ]])

## El argumento keepdims

In [40]:
security_breaches.sum(axis=1, keepdims=True)

array([[6],
       [2],
       [4],
       [5],
       [0]])

In [41]:
security_breaches.sum(axis=0, keepdims=True)

array([[ 3, 10,  4]])

## Sumas acumuladas:  .cumsum()

In [42]:
print('El aaray antes del cumsum: ')
security_breaches

El aaray antes del cumsum: 


array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

In [43]:
print('El array despúes del cumsum: ')
security_breaches.cumsum(axis=0) # suma acumulado en  las columnas 

El array despúes del cumsum: 


array([[ 0,  5,  1],
       [ 0,  7,  1],
       [ 1,  8,  3],
       [ 3, 10,  4],
       [ 3, 10,  4]])

-------------------------
# "Práctica 32"
-------------------------

In [44]:
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])

print('El array de x: ')
print(f'Shape de x:', x.shape)
print("Consume",x.nbytes,"bytes") 
print(x)
print('-----------------------------------')
print('El array de y: ')
print(f'Shape de y: ', y.shape)
print("Consume",y.nbytes,"bytes") 
print(y)
print('-----------------------------------')
# x.dot(y)

El array de x: 
Shape de x: (2, 3)
Consume 24 bytes
[[1 0 4]
 [3 3 1]]
-----------------------------------
El array de y: 
Shape de y:  (3, 2)
Consume 24 bytes
[[2 5]
 [1 1]
 [3 2]]
-----------------------------------


In [45]:
x.dot(y)

array([[14, 13],
       [12, 20]])

## Introducción a vectores y matrices 

Multiplicación fila 1 de x por columna 1 de y:

[1, 0, 4] × [2, 1, 3] = ? 

Para multiplicar la fila 1 de x por la columna 1 de y, multiplicamos cada elemento de la fila por cada elemento de la columna y sumamos los resultados:

1 × 2 = 2    ---->                1 × 5 = 5

0 × 1 = 0    ---->                 0 × 1 = 0

4 × 3 = 12   ---->                 4 × 2 = 8

   *  Total 14     ----->                Total 13 

In [46]:
""" x = [[1, 0, 4], [3, 3, 1]]
    y = [[2, 5], [1, 1], [3, 2]]

result = x.dot(y) = [[1*2 + 0*1 + 4*3, 1*5 + 0*1 + 4*2],
                     [3*2 + 3*1 + 1*3, 3*5 + 3*1 + 1*2]]

result = [[14, 13], [16, 22]] """

' x = [[1, 0, 4], [3, 3, 1]]\n    y = [[2, 5], [1, 1], [3, 2]]\n\nresult = x.dot(y) = [[1*2 + 0*1 + 4*3, 1*5 + 0*1 + 4*2],\n                     [3*2 + 3*1 + 1*3, 3*5 + 3*1 + 1*2]]\n\nresult = [[14, 13], [16, 22]] '

## Fundamentos del objeto de matriz de NumPy 

In [47]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:

print("We just create a ", type(x))
print("\nOur template has shape as" ,x.shape)

print("\nTotal size is",x.size)
print("\nThe dimension of our array is " ,x.ndim)
print("\nData type of elements are",x.dtype)
print("\nIt consumes",x.nbytes,"bytes") 


We just create a  <class 'numpy.ndarray'>

Our template has shape as (2, 3)

Total size is 6

The dimension of our array is  2

Data type of elements are int32

It consumes 24 bytes


In [49]:
x = np.array([[1,2,3],[4,5,6]], dtype = float)
print(x)
print(x.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
48


In [50]:

x = np.array([[1,2,3],[4,5,6]], dtype = complex)
print(x)
print(x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [51]:

x = np.array([[1,2,3],[4,55,6]], dtype = np.uint32)
print(x)
# print('------------------------')
print(x.nbytes)

[[ 1  2  3]
 [ 4 55  6]]
24


In [52]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 consume: ",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 consume: ",x.nbytes, "bytes")

int64 consume:  48 bytes
int32 consume:  24 bytes


In [53]:

x_copy = np.array(x, dtype = float)
x_copy 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [54]:

x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:

Data_Cancer = np.random.rand(100000,100)
print(type(Data_Cancer))
print(Data_Cancer.dtype)
print(f'Con float 64 consume mas bytes: ', Data_Cancer.nbytes)
Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print(f'Con float 32 consume menos bytes: ', Data_Cancer_New.nbytes)

<class 'numpy.ndarray'>
float64
Con float 64 consume mas bytes:  80000000
Con float 32 consume menos bytes:  40000000


## Operaciones con NumPy Array 

In [57]:

my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
print(type(my_array)) 
print(my_array)

<class 'numpy.ndarray'>
[ 2 14  6  8]


In [58]:
my_array +2

array([ 4, 16,  8, 10])

In [59]:
my_array -1

array([ 1, 13,  5,  7])

In [60]:
my_array /2

array([1., 7., 3., 4.])

In [61]:
second_array = np.zeros(4) + 3
second_array 

array([3., 3., 3., 3.])

In [62]:
print(my_array)
print('-------------------')
print(second_array)

print('\n====================')
print(my_array - second_array)

[ 2 14  6  8]
-------------------
[3. 3. 3. 3.]

[-1. 11.  3.  5.]


In [63]:
second_array / my_array 
# print(second_array / my_array )

array([1.5       , 0.21428571, 0.5       , 0.375     ])

La función np.identity() en NumPy devuelve una matriz identidad, que es una matriz cuadrada con unos en la diagonal principal y ceros en todas las demás posiciones.

Por ejemplo, si llamamos a np.identity(4), obtenemos una matriz identidad de 4x4.

La matriz identidad es una matriz especial que, cuando se multiplica por otra matriz, no cambia la matriz original. Es decir, si tenemos una matriz A y la multiplicamos por la matriz identidad I, el resultado es la misma matriz A.

In [64]:
print('second_array antes de identity')
print(second_array)
print('\nsecond array despues de np.identity')
second_array = np.identity(4)
second_array

second_array antes de identity
[3. 3. 3. 3.]

second array despues de np.identity


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
second_array = np.identity(4)+3 #Aqui si suma los elementos 
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [66]:
print(my_array)
print('-------------------')
print(second_array)

print('\n====================')
print(my_array - second_array)

# my_array - second_array  

[ 2 14  6  8]
-------------------
[[4. 3. 3. 3.]
 [3. 4. 3. 3.]
 [3. 3. 4. 3.]
 [3. 3. 3. 4.]]

[[-2. 11.  3.  5.]
 [-1. 10.  3.  5.]
 [-1. 11.  2.  5.]
 [-1. 11.  3.  4.]]


In [67]:
second_array / my_array 

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [68]:
x = np.arange(3,7,0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [69]:
x = np.linspace(1.2, 40.5, num=20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

np.geomspace es una función de NumPy que devuelve un arreglo de números espaciados geométricamente entre dos valores dados.

In [70]:
np.geomspace(1, 625, num=5)

array([  1.,   5.,  25., 125., 625.])

np.logspace es una función de NumPy que devuelve un arreglo de números espaciados logarítmicamente entre dos valores dados.

In [71]:
np.logspace(3, 4, num=5)

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [72]:
np.logspace(np.log10(3) , np.log10(4) , num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [73]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

array([ True, False, False,  True])

In [74]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
np.array_equal(x,y)

False

In [75]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x < y 

array([False,  True,  True, False])

La función np.logical_or devuelve un array con los resultados de la operación lógica "or" (o) entre los elementos de los arrays x -- y

In [76]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_or(x,y)

array([ True,  True, False,  True])

In [77]:
np.logical_and(x,y)

array([False,  True, False, False])

In [78]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

 np.exp(x) devuelve un nuevo array con los valores exponentiales de cada elemento en x. 

 Por ejemplo, si x es el array [1, 2, 3, 4], entonces np.exp(x) devolverá un array con los valores [e^1, e^2, e^3, e^4], donde e es la base del exponente neperiano (aproximadamente 2.718).

In [79]:
x = np.array([1, 2, 3,4 ])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [80]:
print(x)
print('---------')
np.log(x)

[1 2 3 4]
---------


array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [81]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [82]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [86]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
np.sum(x)

36

np.amin(x) is a NumPy function that returns the minimum value in an array x.

In [88]:
np.amin(x)

0

La función np.amax(x) devuelve el valor máximo de un arreglo o matriz x.

In [89]:
np.amax(x)

8

La función np.amin(x, axis=0) devuelve el valor mínimo de cada columna de una matriz x

In [90]:
np.amin(x, axis=0) #axis=0 columna

array([0, 1, 2])

In [91]:
np.amin(x, axis=1)

array([0, 3, 6])

In [92]:
np.percentile(x, 80)

6.4

np.argmax(x) devuelve el índice del elemento con el valor más grande en el array x.

In [93]:
x = np.array([1,-21,3,-3])
np.argmax(x)

2

 np.argmin(x) devuelve el índice del elemento con el valor más pequeño en el array x


In [94]:
np.argmin(x)


1

In [95]:
x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [96]:
np.mean(x)

7.666666666666667

In [97]:
np.mean(x, axis=0) #columnas 

array([11. ,  7.5,  4.5])

In [98]:
np.mean(x, axis=1)#filas 

array([ 3.33333333, 12.        ])

In [99]:
np.median(x)

4.5

In [100]:
np.std(x)

6.394442031083626

## Trabajando con Arrays Multidimensionales 

In [101]:
c = np.ones((4, 4))
print(c)
print(c.ndim)
print(c.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
(4, 4)


In [102]:
multiplicacion= c*c
print(multiplicacion)
print(multiplicacion.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [103]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

El método `np.vstack` (Vertical Stack) es una función de NumPy que permite apilar matrices o arrays verticalmente, es decir, concatenarlos en la dirección vertical.

In [104]:
y = np.arange(15).reshape(3,5) 
x = np.arange(10).reshape(2,5)
print(x)
print(y)
print('--------------------------------')
new_array = np.vstack((y,x))
new_array

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------------------


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

La función `hstack` en NumPy se utiliza para apilar arrays horizontalmente, es decir, concatenar arrays junto a lo ancho. Esto significa que los arrays se unen lado a lado, en lugar de uno encima del otro como lo hace vstack.

In [105]:

y = np.arange(15).reshape(5,3) 
x = np.arange(10).reshape(5,2)
print(x)
print(y)
print('--------------------------------')
print('Apila horizontal')
new_array = np.hstack((y,x))
new_array

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
--------------------------------
Apila horizontal


array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

## Biblioteca Stats 

Se utiliza la función describe de la biblioteca stats para calcular estadísticas descriptivas del arreglo x. La función devuelve varios valores que se asignan a variables individuales:

* n: número de elemento en el arreglo

* min_max: tupla con el mínimo y máximo valor del arreglo

* mean: media del arreglo

* var: varianza del arreglo

* skew: sesgo del arreglo

* kurt: curtosis del arreglo

In [106]:
from scipy import stats

x= np.random.rand(100,10)
print(x.shape)
n, min_max, mean, var, skew, kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

(100, 10)


array([[ 4.99035555e-01,  7.27964334e-02,  6.81818526e-02,
        -1.10834308e+00,  1.74501500e-03,  9.81890859e-01],
       [ 4.91705154e-01,  9.11347369e-02,  2.51752015e-02,
        -1.28788274e+00,  7.07510091e-03,  9.90619661e-01],
       [ 5.03572988e-01,  7.20160445e-02,  4.90911995e-02,
        -1.03364360e+00,  2.16331425e-02,  9.97717259e-01],
       [ 5.02836663e-01,  8.51901874e-02,  1.27952197e-01,
        -1.21939576e+00,  9.32876458e-03,  9.98747072e-01],
       [ 4.81895516e-01,  9.06261050e-02,  9.70022958e-02,
        -1.24546172e+00,  6.38950258e-03,  9.87560419e-01],
       [ 5.09789081e-01,  8.86070771e-02, -6.69124932e-02,
        -1.31916542e+00,  1.41848918e-02,  9.99843536e-01],
       [ 4.92758412e-01,  7.91134830e-02, -2.15397382e-02,
        -1.15623718e+00,  5.10575147e-03,  9.71327545e-01],
       [ 5.24105457e-01,  8.51966570e-02, -1.47002099e-01,
        -1.15079367e+00,  5.67165890e-05,  9.95960745e-01],
       [ 5.29074624e-01,  7.85961051e-02, -6.771

In [107]:
#biblioteca numpy.ma proporciona soporte para matrices y arreglos con valores faltantes o máscaras.
import numpy.ma as ma

x = np.arange(6)
print(x.mean())

#El objeto masked_array es una matriz o arreglo que puede tener valores faltantes o máscaras

masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
masked_array.mean()

#En este caso, la máscara es [1,0,0,0,0,0], lo que significa
#que solo el primer elemento del arreglo x (el 0) es considerado como faltante o máscara.

2.5


3.0

In [109]:

x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan #reemplaza todos los valores menores que 5 con NaN, utilizando la sintaxis x[x < 5] = np.nan.
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [110]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

#isnan de NumPy para crear un arreglo booleano que indica qué elementos de x son NaN (Not a Number).


array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])

## Indexing, Slicing, Reshaping, Resizing (redimensionamiento), Broadcasting (difusión)

In [111]:

x = ["USA","France", "Germany","England"]
x[2]

'Germany'

In [112]:
x = ('USA',3,"France",4)
x[2]

'France'

In [113]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:

x[5]

5

In [115]:

x[-2]

8

In [116]:
x[2:8]


array([2, 3, 4, 5, 6, 7])

In [117]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:

x[2:8:2]


array([2, 4, 6])

In [119]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
x[:,1:3] 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [122]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [123]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

"fancy indexing". x[rows, cols],  Donde rows y cols son arrays que contienen los índices de las filas y columnas que se desean seleccionar, respectivamente.

In [125]:
x[[0,1,2],[0,1,3]]
""" Fila 0, columna 0
    Fila 1, columna 1
    Fila 2, columna 3 """

' Fila 0, columna 0\n    Fila 1, columna 1\n    Fila 2, columna 3 '

In [126]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
np.resize(x,(2,2))

array([[0, 1],
       [2, 3]])

In [129]:
np.resize(x,(6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [130]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
x+y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [131]:
x = np.ones(16).reshape(4,4)
y = np.arange(4)
x*y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [132]:

x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [133]:
y = np.arange(2).reshape(1,2)
y

array([[0, 1]])

In [134]:
x*y

array([[0, 1],
       [0, 3]])