----------------------------------------------------
# **Numpy**
---------------------------

## ‘Vectorized Operations’ en Numpy


Recordemos que los ND-arrays de NumPy son homogéneos: un array sólo
puede contener datos de un único tipo. Por ejemplo, un array puede contener
enteros de 8 bits o números de coma flotante de 32 bits, pero no una mezcla de
ambos. Esto contrasta fuertemente con las listas y tuplas de Python, que no
tienen ninguna restricción en cuanto a la variedad de contenidos que pueden
poseer; una lista dada puede contener simultáneamente cadenas, enteros y
otros objetos. 

NumPy es capaz de delegar la tarea de realizar operaciones matemáticas en los contenidos del array a código C optimizado y compilado. Este proceso se conoce como vectorización. 



Ejemplo 1: Utilizando el método de la suma vectorizada en un array
NumPy. Vamos a comparar el método de suma vectorizada junto con
una operación simple no vectorizada, es decir, el método iterativo para
calcular la suma de números de 0 - 14.999

In [1]:
import numpy as np 
import timeit

Los tiempos se expresan en microsegundos (µs) y nanosegundos (ns). Un microsegundo es igual a 1 millón de nanosegundos.

* 17.5 µs ± 1.4 µs per loop (suma vectorizada): Esto significa que la suma vectorizada toma aproximadamente 17.5 microsegundos para completarse, con una desviación estándar de 1.4 microsegundos.

* 15.2 ns ± 1.35 ns per loop (suma iterativa): Esto significa que la suma iterativa toma aproximadamente 15.2 nanosegundos para completarse, con una desviación estándar de 1.35 nanosegundos.



In [8]:
# Suma vectorizada
print(np.sum(np.arange(15000)))

print('El tiempo que toma en la suma vectorizada: \n', end='')
%timeit np.sum(np.arange(15000))
print('------------------------------------------------------')
#Iterative sum
total = 0 
for item in range(0, 15000):
    total += item
a = total
print('\n' + str(a))
print('El tiempo que toma en la suma iterativa: \n', end='')
%timeit a

112492500
El tiempo que toma en la suma vectorizada: 
17.5 µs ± 1.4 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
------------------------------------------------------

112492500
El tiempo que toma en la suma iterativa: 
15.2 ns ± 1.35 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


Ejemplo 2: Aquí compararemos la función exponencial de NumPy con la función
exponencial de la biblioteca matemática incorporada de Python para calcular el
valor exponencial de cada entrada de un objeto en particular

In [10]:
import numpy as np
import timeit
import math 

print('El tiempo que tarda la operación vectorizada: \n', end=' ')
%timeit np.exp(np.arange(150))

print('--------------------------')

# Operación No vectorizada
print('Tiempo de una operación no vectorizada: \n', end = ' ')
%timeit [math.exp(item) for item in range(150)]

El tiempo que tarda la operación vectorizada: 
 2.78 µs ± 82.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
--------------------------
Tiempo de una operación no vectorizada: 
 21.6 µs ± 1.94 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Suma escalar en Numpy

In [11]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array +3

array([[4, 5, 6],
       [7, 8, 9]])

## Multiplicación escalar en Numpy 

In [14]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

## Suma de dos arrays 

In [18]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array_b = np.array([[0,1,0],[1,0,1]])
array_b

array([[0, 1, 0],
       [1, 0, 1]])

In [20]:
array_a + array_b

array([[1, 3, 3],
       [5, 5, 7]])

## Multiplicación de dos arrays 

In [26]:
array_a = np.array([[1,2,3],[4,5,6]])
print(array_a)
print('-----------')
array_b = np.array([[0,1,0],[1,0,1]])
print(array_b)

[[1 2 3]
 [4 5 6]]
-----------
[[0 1 0]
 [1 0 1]]


In [22]:
array_a*array_b

array([[0, 2, 0],
       [4, 0, 6]])

## Operaciones con salida 'Booleanos'

In [27]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array >2

array([[False, False,  True],
       [ True,  True,  True]])

## Vectorizar código python

In [29]:
array = np.array([['Numpy', 'is', 'awesomw']]) 
array

array([['Numpy', 'is', 'awesomw']], dtype='<U7')

In [33]:
len(array) >2

False

Toma el primer elemento del array, que es la cadena 'Numpy', y devolvería su longitud, que es 5. 

El segundo elemento del array, que es la cadena 'is', y devolvería su longitud, que es 2. 

El tercer elemento del array, que es la cadena 'awesomw', y devolvería su longitud, que es 7.

In [36]:
vectorize_len = np.vectorize(len)
print(vectorize_len)
vectorize_len(array) > 2

array([[ True, False,  True]])

--------------------------------------
## **Broadcasting**
--------------------------------

Es una técnica que permite realizar operaciones aritméticas entre arrays de diferentes formas sin necesidad de que tengan las mismas dimensiones. NumPy ajusta automáticamente las dimensiones de los arrays para que coincidan antes
de realizar la operación.

• Identificación de dimensiones compatibles: NumPy compara las dimensiones de los arrays involucrados en la operación. Las dimensiones compatibles son aquellas
que tienen la misma longitud.

• Relleno de dimensiones no compatibles: Para las dimensiones no compatibles, NumPy agrega dimensiones de tamaño 1 a los arrays más pequeños. Esto se hace de
tal manera que las dimensiones de los arrays coincidan entre sí.

• Operación elemento a elemento: Una vez que los arrays tienen las mismas dimensiones, NumPy realiza la operación aritmética elemento a elemento. Esto significa que la operación se aplica a cada par de elementos correspondientes en los arrays

### Primera regla:

Si dos arrays no tienen el mismo rango, entonces se añadirá una dimensión de 1 al principio del array con menor rango hasta que éstos coincidan. El rango de un array es lo mismo que
su número de elementos.

In [45]:
a = np.arange(5).reshape(1,1,5)
b = np.arange(5)
print(a)
print(b)
print('-----------------------')
print(a.shape)
print(b.shape)

print('---- Sumo los 2 arrays ---------')
c= a + b
print(c)
print(f'El shape de la suma de 2 arrays {a} y {b} es: \n', {c.shape} )

[[[0 1 2 3 4]]]
[0 1 2 3 4]
-----------------------
(1, 1, 5)
(5,)
---- Sumo los 2 arrays ---------
[[[0 2 4 6 8]]]
El shape de la suma de 2 arrays [[[0 1 2 3 4]]] y [0 1 2 3 4] es: 
 {(1, 1, 5)}


In [46]:
a

array([[[0, 1, 2, 3, 4]]])

In [47]:
1+a

array([[[1, 2, 3, 4, 5]]])

### Segunda regla:

Si intentamos sumar estos dos arrays, NumPy repetirá los valores de b hasta crear tres columnas iguales y así poder llevar a cabo la operación

In [48]:
d = np.arange(6).reshape(2,3)
d

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
e = np.array([[100],[200]])
e

array([[100],
       [200]])

In [50]:
d+e

array([[100, 101, 102],
       [203, 204, 205]])

In [53]:
f = np.array([100,200,300])
print(f)
print(f'Shape del array: ', f.shape)

[100 200 300]
Shape del array:  (3,)


In [56]:
g = np.arange(6).reshape(2,3)
print(g)
print(f'Shape del array: ', g.shape)

[[0 1 2]
 [3 4 5]]
Shape del array:  (2, 3)


In [60]:
h = f+g
print(h)
print(f'Shape de la suma de los arrays {f.shape} y {g.shape} es\n: ', h.shape)

[[100 201 302]
 [103 204 305]]
Shape de la suma de los arrays (3,) y (2, 3) es
:  (2, 3)


### Tercera regla: 

Después de aplicar las reglas 1 y 2, las dimensiones de los arrays deben coincidir. Si no es así, la operación no se puede llevar a cabo

In [61]:
print(a)
print(a.shape)

[[[0 1 2 3 4]]]
(1, 1, 5)


In [63]:
g = np.array([1,2])
print(g)
print(g.shape)

[1 2]
(2,)


In [65]:
a + g  # ERROR porque tiene diferentes dimensiones 

ValueError: operands could not be broadcast together with shapes (1,1,5) (2,) 

-------------------------------------------
# Práctica 33 

https://numpy.org/doc/stable/user/basics.broadcasting.html

-----------------------

> Broadcasting

El término Broadcasting(difusión) describe cómo NumPy trata las matrices con diferentes formas durante las operaciones aritméticas. 

Sujeto a ciertas limitaciones, La matriz más pequeña se "difunde" a través de la matriz más grande para que tomen formas compatibles. 

Las operaciones de NumPy generalmente se realizan en pares de matrices en un elemento por elemento. En el caso más simple, las dos matrices deben tienen exactamente la misma forma, como en el siguiente ejemplo:



In [66]:
a = np.array([1,2,3])
b = np.array([2,2,2])
a*b

array([2, 4, 6])

In [68]:
a = np.array([1,2,3])
b = 2
a*b

array([2, 4, 6])

## Normas generales de radiodifusión (Broadcasting)

 Dos dimensiones son compatibles cuando

* son iguales, o

* Uno de ellos es el 1.

Si no se cumplen estas condiciones, se hace una excepción `thrown`, lo que indica que las matrices tienen formas incompatibles.`ValueError`: operands could not be broadcast together.

Ejemplo: 

A      (4d array):  8 x 1 x 6 x 1

B      (3d array):      7 x 1 x 5

Result (4d array):  8 x 7 x 6 x 5

In [73]:
# Create the image array
image = np.random.rand(256, 256, 3)
print(image.shape)

# Create the scale array
scale = np.array([1.0, 2.0, 3.0])
print(scale.shape)

# Use broadcasting to scale the image
result = image * scale
print(result.ndim)

print(result.shape) 

(256, 256, 3)
(3,)
3
(256, 256, 3)


## Matrices difuminables

Ejemplos de array que se pueden combinar

A      (2d array):  5 x 4

B      (1d array):      1

Result (2d array):  5 x 4

---------------------------

A      (2d array):  5 x 4

B      (1d array):      4

Result (2d array):  5 x 4

------------------------------

A      (3d array):  15 x 3 x 5

B      (3d array):  15 x 1 x 5

Result (3d array):  15 x 3 x 5

------------------------------

A      (3d array):  15 x 3 x 5

B      (2d array):       3 x 5

Result (3d array):  15 x 3 x 5

------------------------------

A      (3d array):  15 x 3 x 5

B      (2d array):       3 x 1

Result (3d array):  15 x 3 x 5

Ejemplos de arrays que no se pueden combinar:

A      (1d array):  3

B      (1d array):  4 # trailing dimensions do not match
***********************************

A      (2d array):      2 x 1

B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched

In [76]:
#Un ejemplo de difusión cuando se agrega una matriz 1D a una matriz 2D:

a = np.array([[0,0,0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])

print(a)
print(a.shape)
print('-----------------')
b = np.array([1,2,3])
print(b)
print(b.shape)
print('-----------------')

c = a + b
print(c)
print(c.shape)


[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
(4, 3)
-----------------
[1 2 3]
(3,)
-----------------
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
(4, 3)


La radiodifusión proporciona una forma conveniente de tomar el producto externo (o cualquier otra operación externa) de dos matrices. En el ejemplo siguiente se muestra un Operación de adición externa de dos matrices 1-D:

In [77]:
a = np.array([0,10,20,30])
b = np.array([1,2,3])

a[:, np.newaxis] + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## Un ejemplo práctico: la cuantización vectorial 

In [88]:
from numpy import array, argmin, sqrt, sum

observation = array([111.0, 188.0])
print(observation)
print(f'El shape de observation es: ', observation.shape)
print('-----------------------------------')
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
print(codes)
print(f'El shape de codes es: ', codes.shape)
print('-----------------------------------')

diff = codes - observation    # the broadcast happens here
print(diff)
print(f'El shape de diff es: ', diff.shape)

print('-----------------------------------')
dist = sqrt(sum(diff**2,axis=-1))
print(dist)
print(f'El shape de dist es: ', dist.shape)
argmin(dist)

#En este ejemplo, la matriz se estira para que coincida La forma de la matriz:observation, codes

""" Observation      (1d array):      2
    Codes            (2d array):  4 x 2
    Diff             (2d array):  4 x 2 """

[111. 188.]
El shape de observation es:  (2,)
-----------------------------------
[[102. 203.]
 [132. 193.]
 [ 45. 155.]
 [ 57. 173.]]
El shape de codes es:  (4, 2)
-----------------------------------
[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]]
El shape de diff es:  (4, 2)
-----------------------------------
[17.49285568 21.58703314 73.79024326 56.04462508]
El shape de dist es:  (4,)


' Observation      (1d array):      2\n    Codes            (2d array):  4 x 2\n    Diff             (2d array):  4 x 2 '