## Indexación (indexing) y segmentación (slicing) de arrays 

In [3]:
import numpy as np

In [7]:
array = np.array([2,4,6,8,10])

# Acceder al elemento en la posición del array 
print('Accedemos al elemento del array: ')
print(f'El array de [0]: {array[0]}')
print(f'El array de [1]: {array[1]}')
print(f'El array de [2]: {array[2]}')
print(f'El array de [3]: {array[3]}')
print('\nLa dimensión del array es: ', {array.ndim})
print('\nEl shape del array es: ', {array.shape})

Accedemos al elemento del array: 
El array de [0]: 2
El array de [1]: 4
El array de [2]: 6
El array de [3]: 8

La dimensión del array es:  {1}

El shape del array es:  {(5,)}


In [17]:
sudoku_array = np.array([[1, 2, 3, 4, 5, 6],
                         [7, 8, 9, 10, 11, 12],
                         [13, 14, 15, 16, 17, 18],
                         [19, 20, 21, 22, 23, 24],
                         [25, 26, 27, 28, 29, 30],
                         [31, 32, 33, 34, 35, 36]])

print(f'La dimension del sudoku es: ', {sudoku_array.ndim})
print(sudoku_array)

La dimension del sudoku es:  {2}
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


La dimensión 2 se debe a que el array tiene una estructura de matriz, con 6 filas (PRIMERA DIMENSION) y 6 columnas (SEGUNDA DIMENSIÓN).

In [14]:
# Accedo a la primera fila
print(sudoku_array[0])  # Selecciona la primera fila

print('\nSelecciona todas las filas con (:), y la coma (,) indica que queremos mantener todas las columnas,')
print('y 3 especifica el índice de la columna: ')
print(sudoku_array[:,2]) #[:,]selecciona todas las filas 


[1 2 3 4 5 6]

Selecciona todas las filas con (:), y la coma (,) indica que queremos mantener todas las columnas,
y 3 especifica el índice de la columna: 
[ 3  9 15 21 27 33]


In [15]:
#Selecciono el 16
print(sudoku_array[2,3])

16


In [19]:
#Selecciono el 35
print(sudoku_array[5,4])

35


In [20]:
print(sudoku_array[2,:])

[13 14 15 16 17 18]


### Slicing arrays 1D

In [21]:
array = np.array([2,4,6,8,10])
array[2:4]

array([6, 8])

### Slicing arrays 2D

In [31]:
sudoku_array1 = np.array([[10, 2, 3, 4, 5, 6],
                         [70, 800, 9, 100, 11, 120],
                         [13, 14, 15, 16, 17, 18],
                         [19, 200, 21, 220, 23, 240],
                         [25, 26, 27, 28, 29, 30],
                         [30, 302, 33, 340, 35, 360]])

print(f'La dimension del sudoku es: ', {sudoku_array1.ndim})
print(sudoku_array1)

La dimension del sudoku es:  {2}
[[ 10   2   3   4   5   6]
 [ 70 800   9 100  11 120]
 [ 13  14  15  16  17  18]
 [ 19 200  21 220  23 240]
 [ 25  26  27  28  29  30]
 [ 30 302  33 340  35 360]]


In [33]:
sudoku_array1[1:6:2, 1:6:2]
             #Filas  #Columnas

array([[800, 100, 120],
       [200, 220, 240],
       [302, 340, 360]])

## Ordenando arrays:

In [34]:
np.sort(sudoku_array1)

array([[  2,   3,   4,   5,   6,  10],
       [  9,  11,  70, 100, 120, 800],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  21,  23, 200, 220, 240],
       [ 25,  26,  27,  28,  29,  30],
       [ 30,  33,  35, 302, 340, 360]])

## Filtrado de arrays

Hay 2 formas de filtrar en Numpy: 

* Idexado usando `mask` y `fancy`

* Usando `np.where()`

### Indexando con Boolean mask: 

In [35]:
one_to_five = np.arange(1,6)
one_to_five

array([1, 2, 3, 4, 5])