-----------------------------------
# **NUMPY**
---------------------

NumPy, significa Numerical Python, es una biblioteca de Python especializada en el cálculo numérico y el análisis
de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo
tipo en varias dimensiones, y funciones muy eficientes para su manipulación

Ventajas: el procesamiento de los arrays se realiza mucho más rápido (hasta 50 veces más) que las listas, lo
cual la hace ideal para el procesamiento de vectores y matrices de grandes dimensiones

 ![Texto alternativo](\Imagenes\n2.PNG)

## Tipos: 

* int8, int16, int32, int64 ===>  (Entero con signo) 

* uint8, uint16, uint32, uint64 ===> pueden definirse con diferentes tamaños, y solo pueden almacenar números no negativos.

* float16, float32, float64, float128 ===> flotantes 

* string ===> longitud fija de tipo de string 

* unicode ===> longitud fija de tipo unicode 

## Forma del array (shape)

 ![Texto alternativo](\Imagenes\n1.PNG)

## Dimensiones

 ![Texto alternativo](\Imagenes\n3.PNG)

Un tensor 0D se denomina específicamente Escalar. Un tensor 1D se conoce específicamente como Vector. Un tensor 2D se conoce específicamente como Matriz. Las matrices 3D y de dimensiones superiores son sólo tensores. 

In [3]:
import numpy as np

# 1D Tensor (Vector)
tensor_1d = np.array([1, 2, 3, 4, 5])
print("1D Tensor:")
print(tensor_1d)

1D Tensor:
[1 2 3 4 5]


In [3]:
# 2D Tensor (Matriz)
tensor_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Tensor:")
print(tensor_2d)


2D Tensor:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 3D Tensor
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                      [[7, 8, 9], [10, 11, 12]], 
                      [[13, 14, 15], [16, 17, 18]]])
print("3D Tensor:")
print(tensor_3d) 


3D Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [5]:
# 4D Tensor
tensor_4d = np.array([[[[1, 2, 3], [4, 5, 6]], 
                       [[7, 8, 9], [10, 11, 12]]], 

                      [[[13, 14, 15], [16, 17, 18]], 
                       [[19, 20, 21], [22, 23, 24]]]])
print("4D Tensor:")
print(tensor_4d) 

4D Tensor:
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]


### Aplanar imágenes

In [11]:
from PIL import Image
imagen = Image.open('Imagenes/n1.PNG')

In [14]:
#Convierte la imagen a escala de grises
imagen_gris = imagen.convert('L')
print(imagen_gris)

<PIL.Image.Image image mode=L size=762x374 at 0x1747A240CD0>


In [13]:
#Convierte la imagen a un array NumPy
imagen_array = np.asarray(imagen_gris)

In [17]:
#Aplana el array
imagen_plana = imagen_array.flatten()
print(imagen_plana)

[255 255 255 ... 255 255 255]


## Creación de arrays 

Para crear un array se utiliza la siguiente función de NumPy:
* np.array(lista) : Crea un array a partir de la lista o tupla lista y devuelve una referencia a él. El número de dimensiones del array dependerá de las listas o tuplas anidadas en lista:
* Para una lista de valores se crea un array de una dimensión, también conocido como vector.
* Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como matriz.
* Para una lista de listas de listas de valores se crea un array de tres dimensiones, también conocido como cubo.

Y así sucesivamente. No hay límite en el número de dimensiones del array más allá de la memoria disponible en el sistema.

In [2]:
import numpy as np 

### Array de una dimensión

In [12]:
# Array de una dimnesión 

a1 = np.array([1,2,3])
print(a1)

[1 2 3]


### Array de dos dimensiones

In [14]:
# Array de dos dimnesiones

a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


### Array de tres dimensiones

In [5]:
# Array de tres dimesiones 
a3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[8,7,6]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 7 6]]]


### Array de cuatro dimensiones

In [7]:
# Array de cuatro dimesiones 
a3 = np.array([[[[1,2,3],[4,5,6]], [[7,8,9],[8,7,6]]], [[[12,22,32],[42,52,62]], [[72,82,92],[82,72,62]]]])
print(a3)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [ 8  7  6]]]


 [[[12 22 32]
   [42 52 62]]

  [[72 82 92]
   [82 72 62]]]]


### Array de cinco dimensiones

In [9]:
a4 = np.array([[[[[1,2,3],[4,5,6]], [[7,8,9],[8,7,6]]], [[[12,22,32],[42,52,62]], [[72,82,92],[82,72,62]]], [[[12,22,32],[42,52,62]], [[702,802,902],[802,702,602]]]]])
print(a3)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [ 8  7  6]]]


 [[[12 22 32]
   [42 52 62]]

  [[72 82 92]
   [82 72 62]]]]


## Verificando el número de dimensiones 

In [14]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(f'La dimensión del array a: {a.ndim}')
print(f'La dimensión del array b: {b.ndim}')
print(f'La dimensión del array c: {c.ndim}')
print(f'La dimensión del array d: {d.ndim}')

La dimensión del array a: 0
La dimensión del array b: 1
La dimensión del array c: 2
La dimensión del array d: 3


In [19]:
array_1_2D = np.array([[1,3], [4,5]])
array_2_2D = np.array([[11,31], [44,55]])
array_3_2D = np.array([[100,300], [400,500]])
array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print(array_1_2D)

[[1 3]
 [4 5]]


In [20]:
print(array_2_2D)

[[11 31]
 [44 55]]


In [21]:
print(array_3_2D)

[[100 300]
 [400 500]]


In [22]:
print(array_3D)

[[[  1   3]
  [  4   5]]

 [[ 11  31]
  [ 44  55]]

 [[100 300]
  [400 500]]]


In [24]:
print(array_3D.ndim)

3


## Construyendo arrays con `ndmin`
El parámetro `ndmin` se utiliza para especificar el número mínimo de dimensiones. 

In [26]:
array_a = np.array([[1,2,3,4,5,6], [9,10,11,14,15,16]], ndmin = 5)
print(array_a)

[[[[[ 1  2  3  4  5  6]
    [ 9 10 11 14 15 16]]]]]


In [48]:
#Construeyndo arrays con ndim 
array_5 = np.array([1,2,3, 4], ndmin=5)
print(array_5)

[[[[[1 2 3 4]]]]]


## Otras funciones para crear arrays 

* np.zeros()
* np.random.random()
* np.arange()

### np.zeros()

In [50]:
# Crea un array con shape(5,3) es decir: 
#5 filas y 3 columnas, y todos los elementos se inicializan con el valor 0.0

np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### np.random.random()

In [55]:
a = np.random.random((2,4,3))
print(a)

[[[0.90141061 0.06242253 0.96304465]
  [0.58417649 0.37715457 0.28094854]
  [0.45380436 0.19509499 0.39391227]
  [0.4254745  0.48720317 0.18299548]]

 [[0.22555946 0.92647334 0.45882309]
  [0.89018447 0.66845844 0.32199477]
  [0.30332304 0.85852508 0.23982318]
  [0.53442954 0.90942757 0.63961527]]]


In [56]:
print(a.shape)

(2, 4, 3)


### np.arange

In [57]:
np.arange(-3,4) # va desde el -3 hasta el 4

array([-3, -2, -1,  0,  1,  2,  3])

In [58]:
np.arange(4)


array([0, 1, 2, 3])

In [61]:
np.arange(-3,4, 3) #array de 3 hasta el 4 de 3 en tres 


array([-3,  0,  3])

## Cambio de forma: Shapeshifting

> Atributos:
.shape

> Métodos:
.flatten() 
.reshape()


### .shape()

In [63]:
array = np.zeros((3,5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [64]:
array.shape

(3, 5)

In [70]:
a= np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [72]:
print(a.ndim)

2


In [73]:
a.shape

(5, 3)

### .flatten()

In [74]:
array_1 = np.array([[1,2],[5,7],[6,6]])
array_1.ndim

2

In [75]:
print(array_1)

[[1 2]
 [5 7]
 [6 6]]


In [77]:
array_1.flatten()

array([1, 2, 5, 7, 6, 6])

In [79]:
array_1.flatten().ndim

1

### .reshape()

In [81]:
array_2 = np.array([[10,20],[50,70],[60,60]])
print(array_2)

[[10 20]
 [50 70]
 [60 60]]


In [82]:
array_2.ndim # Retorne el número de dimensiones en el array
#el array tiene 2 dimensiones: filas y columnas.

2

In [83]:
array_2.shape # forma del array como tupla 

(3, 2)

In [84]:
array_2.reshape((2,3))

array([[10, 20, 50],
       [70, 60, 60]])

In [85]:
array_2.reshape((2,3)).ndim # el array tiene 2 dimensiones: filas y columnas.

2

In [86]:
array_2.reshape(6)

array([10, 20, 50, 70, 60, 60])

Un array con 3 dimensiones en NumPy se conoce como un tensor o un array 3D. En este caso, las 3 dimensiones son:

*Filas (o eje 0)

*Columnas (o eje 1)

*Profundidad (o eje 2)

In [91]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],  # fila 1, columna 1
    [[7, 8, 9], [10, 11, 12]],  # fila 1, columna 2
    [[13, 14, 15], [16, 17, 18]]  # fila 2, columna 1
])

print(array_3d.shape) 
#La forma del array array_3d es indeed (3, 2, 3), lo que indica que tiene:
#3 filas (eje 0), 2 columnas (eje 1), 3 elementos de profundidad (eje 2)

(3, 2, 3)


In [88]:
array_3d.ndim

3

----------------------
# **Una guía completa de los tipos de datos de NumPy**    
-------------------------

¿Qué más hay además de int32 y float64? 

Existen 7 tipos: 

* 1) Integers (enteros)
* 2) Float (flotantes)
* 3) Boleanos
* 4) Strings (cadenas)
* 5) Datetimes 
* 6) Combinations thereof
* 7) Type Checks



## 1) Integers (enteros)

`'u'` significa 'sin signo' y los `dígitos` representan el número de bits utilizados para almacenar la variable en la memoria

 ![Texto alternativo](\Imagenes\np1.PNG)

In [29]:
np.array([1,2,3]).dtype
# int32 en Windows, int64 en Linux y MacOS 

dtype('int32')

 Cada elemento en el arreglo se representará como un entero sin signo de 8 bits, que puede almacenar valores desde 0 hasta 255.

  Sumar 1 al elemento único 255, normalmente daría como resultado 256. Sin embargo, debido al desbordamiento de entero sin signo, el valor se envuelve alrededor de 0.

  Si desea evitar este comportamiento, considere utilizar enteros con signo: np.int16 o np.int32

In [30]:
np.array([255], np.uint8) +1  #Es:2**8-1, maximo uint8

# suma 1 al elemento único 255.

array([0], dtype=uint8)

In [31]:
np.array([2**31-1]) #Para int32

array([2147483647])

In [32]:
np.array([2**31-1]) +1

array([-2147483648])

In [34]:
np.array([2**630-1]) +1 #np.int64

array([4455508415646675018204269146191690746966043464109921807206242693261010905477224010259680479802120507596330380442963288389344438204468201170168614570041224793214838549179946240315306828365824],
      dtype=object)

In [36]:
a = np.array([10], dtype = object)
len(str(a**1000))

1003

## 2) Floats (flotantes)
Como el float puro de Python no divergió del tipo doble de C estandarizado por IEEE 754 (nótese la diferencia en la nomenclatura), la transición de los números de coma flotante de Python a NumPy es prácticamente sin problemas: Python float es directamente compatible con np.float64 y Python complex — con np.complex128 .


In [39]:
x = np.array([-1234.5], dtype=np.float128) # Da error porque el float 128 está disponible en Linux y Mac
# 1/(1+np.exp(-x))


AttributeError: module 'numpy' has no attribute 'float128'

Para los datos financieros decimales. El tipo decimal es útil ya que no implica tolerancias adicionales en absoluto:

In [40]:
from decimal import Decimal as D 

a = np.array([D('0.1'), D('0.2')]);a

array([Decimal('0.1'), Decimal('0.2')], dtype=object)

In [41]:
a.sum()

Decimal('0.3')

In [44]:
#Para cálculos matemáticos puros, fracciones. La fracción se puede utilizar:

from fractions import Fraction

np.array([Fraction(1, 10), Fraction(1, 5)], dtype=object)

array([Fraction(1, 10), Fraction(1, 5)], dtype=object)

In [45]:
#Los números complejos se tratan de la misma manera que los flotantes. 
np.array([1+2j])

array([1.+2.j])

## 3) Booleano

Los valores booleanos se almacenan como bytes individuales para un mejor rendimiento.

A día de hoy, np.bool sigue funcionando, pero muestra una advertencia de obsolescencia.

In [93]:
import sys
sys.getsizeof(True)

28

## 4) Strings 

Al inicializar una matriz NumPy con una lista de cadenas de Python, se empaquetan en un tipo de NumPy nativo de ancho fijo llamado np.str_ . Reservar un espacio necesario para que quepa la cadena más larga para cada elemento puede parecer un desperdicio (especialmente en la codificación USC-4 fija en lugar de la elección 'dinámica' del ancho UTF en Python str)

In [95]:
np.array(['abcde', 'x', 'y', 'x']) #4 bytes por un caracter  
#5*4 bytes por elemento

array(['abcde', 'x', 'y', 'x'], dtype='<U5')

In [97]:
np.array(['abcde', 'x', 'y', 'x'], object) #1byte por cada ascii caracter

array(['abcde', 'x', 'y', 'x'], dtype=object)

In [99]:
np.array([b'abcde', b'x', b'y', b'x']) #1 byte por ascii caracter 
#5bytes por elemento

array([b'abcde', b'x', b'y', b'x'], dtype='|S5')

In [102]:
np.char.upper(np.array([['a','b'],['c','d']]))


array([['A', 'B'],
       ['C', 'D']], dtype='<U1')

In [104]:
#Con las cadenas en modo objeto, los bucles deben ocurrir en el nivel de Python:
a=np.array([['a','b'],['c','d']])
np.vectorize(lambda x: x.upper(), otypes=[object])(a)

array([['A', 'B'],
       ['C', 'D']], dtype=object)

## 5) Datetimes

Timestamp (también conocido como tiempo de Unix, el número de segundos desde el 1 de enero de 1970 A.C)

La granularidad de los años significa que "solo cuenta los años", no hay una mejora real en comparación con el almacenamiento de años como un número entero. La granularidad de días es un equivalente de datetime.date de Python . Microsegundos — de datetime.datetime de Python .

#Al crear una instancia de np.datetime64 , NumPy elige la granularidad más gruesa que aún puede contener dichos datos

In [106]:
np.datetime64('today') #Granularidad (en tiempo local UTC+7)

numpy.datetime64('2024-06-18')

In [108]:
np.datetime64('now') #Granularidad en segundos (en UTC)

numpy.datetime64('2024-06-18T19:15:12')

In [114]:
import datetime as dt
np.datetime64(dt.datetime.utcnow()) #Granularidad en microsegundos

numpy.datetime64('2024-06-18T19:18:26.578650')

In [116]:
np.datetime64('2024-06-18T19:18:26.578650') #Granularidad de nanosegundos

numpy.datetime64('2024-06-18T19:18:26.578650')

## 6) Combinations thereof

Una 'matriz estructurada' en NumPy es una matriz con un tipo de archivo personalizado hecho de los tipos descritos anteriormente como los bloques de construcción básicos (similar a struct en C). Un ejemplo típico es un color de píxel RGB: un tipo de 3 bytes de largo (generalmente 4 para la alineación), en el que se puede acceder a los colores por su nombre:

In [3]:
rgb = np.dtype([('x', np.uint8), ('y', np.uint8), ('z', np.uint8)])
a = np.zeros(5, dtype=rgb)
print(a)

[(0, 0, 0) (0, 0, 0) (0, 0, 0) (0, 0, 0) (0, 0, 0)]
